# Least-Liked Groups: ordinal item-response model {#llg}

In a public opinion survey in France [@GrunbergMayerSniderman2002a], 1,941 respondents identified their "least-liked group" from a list of four groups: Communist Revolutionaries, the National Front, Muslum fundamentalists, and Scientologists.  Respondents were then asked if they thought their least-liked group should be permitted to hold a public rally: the responses were coded as "Strongly Agree", "Agree", "Disagree", "Strongly Disagree".  At two subsequent stages in the interview, respondents were asked the same question about groups randomly-selected from the three groups not designated as the least-liked group; this repeated trials design lets us assess the impact of the "least-liked" designation on respondents' tolerance and committment to civil liberties.
The observed data consist of a set of 3 responses for each respondent, with the first response referring to each respondent's "least-liked group".  We model these data with a ordinal logistic model, in which the latent trait, tolerance (tol), is embedded as a respondent-specific parameter.  In effect, this is an item-response model, with the complications that (a) the test consists of just three items, and so the posteriors for tol are only modestly shifted away from their N(0,1) common prior; (b) the responses are ordinal.  We recover two parameters per group (beta, the analogs of item discrimination and item difficulty parameters, designated beta in the code below), and two contrasts per group (delta), tapping increases in item-difficulty and item-discrimination associated with the "least-liked" group on the first trial.  We also estimate 2 group-specific threshold parameters (gamma); since we include group-specific intercepts in the model, we set the threshold parameter between responses 1 and 2 to zero.

It would also be straightforward to extend the model, replacing the N(0,1) prior for each respondent's latent level of tolerance with a hierarchical structure with respondent-specific covariates (e.g., social-structural indicators such as age, gender, education, or occupation; or political characteristics such as party affiliation, ideological orientation, and so on).

model
{
  for (i in 1:1941){
    mu[i,1] <- beta[g[i,1],1] + delta[g[i,1],1] +
               (beta[g[i,1],2] + delta[g[i,1],2])*tol[i];
    for (j in 2:3){
      mu[i,j] <- beta[g[i,j],1] + beta[g[i,j],2]*tol[i];
    }

    for (j in 1:3){
      logit(Q[i,j,1]) <- -mu[i,j];   ## threshold set to zero
      logit(Q[i,j,2]) <- gamma[g[i,j],1] - mu[i,j];
      logit(Q[i,j,3]) <- gamma[g[i,j],2] - mu[i,j];

      p[i,j,1] <- Q[i,j,1];
      p[i,j,2] <- Q[i,j,2] - Q[i,j,1];
      p[i,j,3] <- Q[i,j,3] - Q[i,j,2];
      p[i,j,4] <- 1 - Q[i,j,3];     ## cumulative model probs

      y[i,j] ~ dcat(p[i,j,]);
    }
  }

  ## priors
  for (i in 1:1941){
    tol[i] ~ dnorm(0.0,1.0);
  }

  for (j in 1:4){
    beta[j,1:2]  ~ dmnorm(b0[],B0[,]);
    delta[j,1:2] ~ dmnorm(b0[],B0[,]);
    gamma[j,1] ~ dnorm(0,.01)I(0,);
    gamma[j,2] ~ dnorm(0,.01)I(gamma[j,1],);
  }

  b0[1] <- 0.0; b0[2] <- 0.0;
  B0[1,1] <- .01; B0[1,2] <- 0.0;
  B0[2,1] <- 0.0; B0[2,2] <- .01;

}


Data:

list(y = structure(
       .Data=c(4., 4., 4., 2., 4., 4., 4., 2., 1., 4., 1., NA, 4.,
       2., 4., 2., 3., 1., 2.,
	3., 2., 3., 3., 2., 2., 4., 4., 2., 4., 1., 2., 2., 2., 1., 1., 2.,
	NA, 2., 2., 3., 3., 3., 3., 1., 3., 3., 2., 3., 4., 4., 1., 4., 3.,
	2., 3., 4., 2., 2., 2., 2., 3., 4., 1., 4., 2., 2., 1., 3., 4., 2.,
	2., 1., 4., 4., 4., 4., 3., 3., 4., 3., 4., 4., 4., 4., 4., 2., 2.,
	4., 2., 4., 3., 2., 2., 4., 2., 4., 4., 2., 2., 2., 2., 3., 1., 2.,
	1., 4., 4., 4., 4., 3., 3., 3., 2., 2., 2., 2., 2., 4., 4., 3., 4.,
	3., 3., 4., 2., 3., 2., 1., 2., 4., 4., 2., 2., 2., 2., 3., 2., 3.,
	4., 2., 1., 1., 2., 2., 4., 4., 4., 4., 2., 3., 4., 2., 1., 4., 3.,
	4., 3., 3., 3., 4., 3., 3., 1., 2., 1., 1., 1., 4., 2., 1., 3., 4.,
	4., 4., 2., 2., 2., 4., 4., 2., 4., 4., 2., 2., 3., 1., 4., 1., 3.,
	4., 4., 4., 1., 2., 2., 1., 1., 1., 1., 3., 1., 4., 4., 3., 4., 2.,
	2., 4., 4., 3., 4., 3., 3., 4., 3., 3., 2., 2., 4., 3., 2., 3., 2.,
	1., 4., 2., 3., 3., 2., 3., 2., 2., 2., 1., 2., 4., 4., 4., 3., 2.,
	3., 3., 2., 2., 1., 2., 4., 3., 1., 4., 4., 1., 4., 4., 1., 4., 2.,
	3., 2., 1., 2., 4., 1., 2., 4., 4., 3., 3., 2., 3., 4., 2., 1., 4.,
	1., 2., 4., 2., 3., 2., 1., 2., 3., 4., 1., 3., 3., 3., 4., 1., 2.,
	2., 2., 2., 3., 2., 2., 2., 2., 2., 2., 4., 3., 3., 2., 4., NA, 2.,
	1., 4., 4., NA, 2., 4., 2., 4., 2., 1., 2., 2., 3., 2., 4., 4., 3.,
	2., 2., 2., 3., 2., 3., 1., 4., 4., 2., 2., 3., 3., 1., 4., 1., 1.,
	4., 2., 2., 1., 2., 2., 3., 4., 2., 3., 3., 2., 1., 2., 2., 4., 2.,
	1., 4., 2., 3., 4., 4., 4., 4., 4., 4., 4., 1., 3., 4., 3., 2., 2.,
	2., 2., 2., 4., 2., 4., 3., 4., 4., 2., 4., 2., 4., 4., 3., 2., 2.,
	4., 2., 3., 4., 3., 4., 2., 2., 3., 3., 2., 2., 2., 3., 3., 2., 1.,
	1., 4., 4., 2., 2., 4., 2., 1., 4., 3., 2., 2., 4., 2., 4., 2., 4.,
	1., 1., 2., 2., 2., 1., 1., 1., 3., 4., 1., 2., 1., 2., 4., 1., 4.,
	4., 4., 3., 3., 2., 1., 4., 3., 3., 2., 3., 1., 4., 3., 2., 2., 2.,
	3., 4., 4., 1., 2., 3., 2., 2., 2., 4., 3., 3., 1., 3., 4., 4., 4.,
	4., 4., 4., 4., 4., 4., 4., 4., 3., 3., 2., 4., 4., 3., 4., 4., 3.,
	4., 1., 1., 1., 1., 1., 2., 2., 4., 4., 4., 1., 2., 2., 4., 3., 3.,
	NA, 1., 1., 2., 4., 3., 4., 3., 2., 2., 3., 2., 2., 2., 1., 1., NA,
	NA, NA, 1., 3., 4., 2., 4., 2., 4., 3., 4., 2., 4., 3., 4., 3., 2.,
	1., 4., 1., 1., 4., 4., 4., 1., 1., 2., 1., 1., 4., 2., 1., 2., 3.,
	3., 3., 3., 1., 2., 2., 4., 4., 2., 3., 2., 4., 4., 4., 2., 2., 1.,
	1., 1., 4., 2., 2., 4., 2., 4., 2., 2., 2., 3., 2., 2., 2., 2., 2.,
	2., 2., 4., 1., 4., 2., 2., 2., 3., 3., 3., 3., 3., 4., 2., 2., 1.,
	3., 2., 2., 4., 2., 3., 4., 4., 3., 2., 4., 2., 3., 4., 3., 4., 4.,
	4., 3., 3., 2., 2., 4., 4., 4., 2., 3., 2., 3., 2., 2., 4., 1., 3.,
	1., 2., 2., 3., 2., 2., 4., 3., 3., 4., 1., 1., 4., 3., 1., 4., 2.,
	1., 4., 2., 3., 4., 2., 2., 2., 1., 4., 2., 3., 3., 4., 2., 2., 2.,
	1., 1., 2., 3., 2., 4., 2., 2., 4., 4., 4., 2., 1., 2., 4., 2., 4.,
	2., 4., NA, 4., 2., 3., 4., 4., 4., 4., 4., 3., 3., 4., 3., 1., 2.,
	1., 1., 2., 2., 2., 3., 1., 3., 4., 3., 4., 3., 3., 4., NA, 1., 1.,
	2., 1., 4., 2., 2., 3., 1., 3., 4., 4., 2., 2., 3., 4., 4., 2., 2.,
	3., 2., 1., 1., 2., 3., 3., 2., 2., 1., 3., 4., 4., 3., 4., 2., 2.,
	2., 4., 4., 4., 3., 4., 4., 4., 3., 4., 4., 4., 1., 3., 2., 3., 2.,
	1., 2., 4., 4., 4., 4., 2., 4., 4., 1., 4., 2., 1., 1., 2., 1., 4.,
	2., 4., 1., 2., 3., 2., 4., 2., 3., 1., 1., 3., 3., 2., 4., 2., 2.,
	2., 4., 2., 4., 3., 4., 2., 3., 3., 3., 4., 4., 2., 4., 3., 3., 2.,
	4., 3., NA, 1., 4., 1., 1., 1., 1., 4., 4., 2., 2., 2., 4., 4., 4.,
	2., 2., 2., 4., 3., 4., 2., 2., 2., 4., 4., 4., 4., 2., 1., 4., 4.,
	4., 4., 4., 3., 4., 4., 4., 3., 2., 1., 4., 2., 2., 3., 3., 3., 4.,
	1., 3., 3., 2., 3., 2., 4., 1., 2., 2., 4., 1., 1., 1., 2., 2., 2.,
	1., 1., 1., 1., 3., 2., 4., 3., 4., 4., 3., 2., 3., 3., 3., 4., 4.,
	3., 3., 2., 3., 2., 2., 2., 4., 1., 4., 3., 4., 3., 4., NA, 3., 1.,
	1., 1., 4., 4., 4., 4., 4., 1., 2., 2., 3., 4., 4., 4., 3., 1., 3.,
	3., 3., 4., 2., 3., 2., 3., 4., 4., 1., 1., 2., 1., 2., 2., 2., 3.,
	1., 2., 3., 3., 3., 2., 4., 4., 1., 2., 3., 2., 3., 4., 3., 4., 4.,
	4., 2., 4., 4., 4., 4., 1., 2., 2., 4., 3., 4., 1., 3., 3., 4., 3.,
	2., 1., 2., 4., 3., 2., 1., 1., 2., 1., 1., 1., 1., 4., 3., 2., 3.,
	3., 4., 3., 2., 4., 2., 4., 2., 3., 2., 3., 2., 4., 2., 3., 2., 1.,
	3., 1., 4., 2., 2., 4., 3., 4., 3., 1., 4., 4., 2., 3., 4., 2., 4.,
	4., NA, NA, 3., 2., 3., 1., 2., 4., 4., 1., 4., 4., 1., 4., 4., 4.,
	2., 1., 4., 1., 4., 4., 1., 4., 2., 2., 2., 2., 3., 4., 2., 3., 3.,
	3., 3., 4., 1., 3., 3., 1., 3., 4., 3., 3., 4., 3., 4., 1., 1., 4.,
	2., 3., 2., 2., 2., 2., 4., 1., 2., 4., 3., 2., 2., 4., 3., 2., 3.,
	2., 4., 4., 1., 4., 4., 4., 4., 3., 2., 4., 1., 3., 3., 2., 2., 4.,
	2., 2., 4., 4., 4., 4., 1., 2., 2., 2., 2., 4., 4., 2., 1., 4., 4.,
	3., 1., 1., 2., 2., 3., 4., 2., 3., 2., 1., 4., 1., 1., 1., 3., 4.,
	2., 4., 2., 3., 3., 2., 1., 4., 4., 4., 4., 2., 2., 2., 2., 4., 3.,
	1., 3., 2., NA, 2., 4., 3., 3., 4., 2., 4., 4., 2., 2., 3., 2., 1.,
	2., 4., 1., 3., 3., 4., 4., 2., NA, 4., 1., 4., 4., 1., 2., 1., 2.,
	2., 3., 2., 3., 2., 4., 4., 2., 2., 2., 4., 3., 3., 4., 1., 3., 3.,
	3., 3., 4., 1., NA, 2., 1., 1., 3., 2., 2., 4., 2., 4., 4., 2., 2.,
	4., 4., 2., 4., 3., 3., 4., 3., 4., 2., 2., 2., 4., NA, 2., 2., 2.,
	4., 4., 1., 1., 1., 2., 3., 2., 1., 1., 2., 2., 2., 4., 1., 1., 3.,
	2., 3., 2., 4., 1., 4., 1., 4., 4., 3., 1., 2., 2., 3., 4., 2., 4.,
	1., 1., 4., 3., 3., 2., 2., 1., 2., 3., 3., 3., 4., 2., 3., 4., 3.,
	1., 2., 1., 4., 3., 3., 3., 3., 4., 2., 2., 4., 4., 2., 4., 4., 3.,
	2., 3., 2., 4., 1., 4., 4., 3., 2., 2., 2., 4., 4., 4., 1., 4., 4.,
	4., 4., 4., 2., 4., 1., 4., 2., 4., 1., 2., 2., 4., 4., 4., 4., 4.,
	3., 2., NA, 2., 3., 3., 2., 1., 4., 3., 4., 4., 4., 2., 2., 2., 4.,
	2., 1., 2., 4., 3., 4., 1., 1., 4., 2., 4., 1., 2., 1., 2., 4., 1.,
	2., 2., NA, 1., 3., 2., 4., 4., 3., 4., 4., 4., 2., 3., 3., 1., 2.,
	3., 2., 2., 2., 3., 4., 2., 1., 2., 3., 3., 2., 3., 1., 4., 2., 4.,
	4., 1., 2., 1., 3., 2., 3., 3., 4., 3., 2., 4., 3., 4., 2., 2., 1.,
	4., 3., 3., 2., 2., 3., 4., 4., 1., 2., 4., 4., 2., 1., 1., 4., 1.,
	4., 2., 1., 4., 2., 1., 4., 2., 2., 2., 3., 2., 4., 4., 4., 4., 4.,
	3., 2., 4., 4., 2., 3., 4., 3., 4., 1., 4., 2., 2., 2., 2., 4., 2.,
	4., 3., 4., 4., 2., 2., 4., 3., 3., 3., 3., 3., 4., 3., 1., 2., 1.,
	2., 2., 1., 4., 4., 1., 2., 4., 4., 4., 1., 4., 1., 2., 2., 4., 4.,
	3., 3., 4., 4., 1., 4., 1., 3., 4., 2., 4., 4., 4., 4., 4., 4., 4.,
	3., 1., 3., 4., 4., 1., 4., 4., 4., 4., 2., 1., 4., 2., 1., 3., 2.,
	3., 2., 1., 2., 2., 2., 1., 4., 2., 2., 4., 3., 3., 4., 3., 3., 4.,
	2., 4., 3., 2., 1., 2., 1., 3., 3., 3., 3., 1., 4., NA, 3., 2., 4.,
	4., 3., 2., NA, 2., 1., 4., 2., 3., 4., 1., 4., 3., 4., 4., 2., 2.,
	4., 2., 4., 4., 1., 4., 1., 4., 3., 3., 3., 3., 3., 2., 4., 3., 1.,
	2., 2., 4., 4., 1., 4., 2., 4., 4., 2., NA, 3., 3., 2., 4., 2., 3.,
	4., 4., 2., 3., 2., 3., 2., 2., 2., 1., 2., 1., 4., 1., 3., 2., 2.,
	2., 4., 3., 2., 4., 2., 4., 2., 3., 2., 2., 2., 2., 4., 2., 3., 1.,
	3., 1., 4., 2., 4., 3., 4., 2., 1., 1., 4., 2., 4., 2., 4., 4., 4.,
	2., 3., 4., 3., 3., 3., 4., 4., 4., 2., 4., 2., 2., 1., 1., 4., 4.,
	4., 4., 1., 2., 4., 4., 3., 2., 2., 2., 2., 4., 2., 4., 2., 3., 4.,
	NA, 3., 2., 2., 2., 4., 2., 4., 4., 1., 4., 1., 1., 1., 4., 4., 4.,
	2., 2., 2., 3., 4., 3., 1., 1., 2., 4., 4., 4., 3., 3., 4., 2., 2.,
	2., 4., 2., 3., 2., 3., 3., 1., 1., 1., 4., 4., 4., 4., 4., 1., 4.,
	1., 1., 2., 1., 1., 2., NA, 3., 4., 4., 3., 2., 2., 2., NA, 2., NA,
	4., 4., 1., 4., 1., 1., 4., 4., 4., 4., 3., 3., 4., 4., 4., 2., 2.,
	2., 4., 1., 4., 4., 1., 4., 4., 2., 4., 1., 1., 3., 3., 2., 3., 4.,
	4., 2., 4., 4., 1., 3., 2., 3., 4., 4., 4., 3., NA, 2., 4., 3., 4.,
	4., 3., 3., 2., 4., 4., 4., 2., 4., 2., 4., 3., 1., 1., 4., 4., 1.,
	3., 4., 2., 4., 2., 2., 2., 4., 1., 4., 2., 1., 4., 2., 2., 2., 1.,
	2., 2., 4., 4., 4., 2., 4., 4., 4., 4., 4., 3., 3., 4., 4., 4., 3.,
	4., 4., 4., 2., 2., 2., 4., 2., 4., 2., 2., 2., 2., 2., 4., 1., 2.,
	4., 4., 2., 2., 2., 1., 2., 3., 2., 4., 4., 3., 3., 1., 2., 1., 4.,
	4., 4., 2., 1., 1., 2., 3., 3., 4., 3., 3., 3., 3., 3., 4., 1., 4.,
	4., 1., 2., 1., 2., 2., 1., 2., 2., 4., 1., 4., 4., 4., 3., 2., 2.,
	4., 2., 4., 4., 1., 1., 1., 2., 2., 2., 1., 2., 2., 4., 2., 4., 4.,
	4., 4., 4., 3., 3., 3., 1., 2., 1., 1., 1., 4., 2., 3., 4., 4., 1.,
	3., 3., 3., 2., 4., 1., 1., 1., 1., 4., 4., 1., 1., 1., 1., 4., 2.,
	2., 4., 4., 3., 2., 1., 3., 3., 2., 2., 3., 2., 4., 3., 3., 2., 4.,
	1., 1., 4., 2., 1., 2., 1., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3.,
	3., 4., 2., 4., 1., 4., 4., 4., 1., 4., 2., 1., 2., 2., 2., 2., 1.,
	1., 1., 2., 1., 2., 2., 2., NA, 3., 4., 2., 4., 2., 4., 3., 3., 1.,
	2., 2., 3., 3., 3., 2., 4., 2., 2., 3., 2., 3., 3., 3., 1., 4., 4.,
	2., 1., 4., 1., 2., 4., 1., 4., 2., 1., 3., 3., 4., 1., 1., 2., 3.,
	4., 3., 3., 3., 4., 3., 2., 1., 3., 4., 1., 2., 1., 4., 1., 2., 1.,
	1., 3., 4., 4., 3., 4., 3., 3., 2., 1., 4., 4., 4., 3., 4., 4., 3.,
	2., 4., 4., 3., 3., 1., 2., 2., 2., 1., 1., 2., 2., 4., 2., 4., 1.,
	1., 4., 4., 1., 3., 4., 1., 2., NA, 2., 3., 4., 3., 3., 3., 3., 3.,
	3., 2., 4., 3., 4., 4., 2., 2., 3., 4., 4., 2., 2., 4., 4., 4., 2.,
	1., 1., 1., 1., 3., 2., 2., 2., 3., 4., NA, 2., 2., 2., 2., 3., 2.,
	1., 1., 1., 3., 2., 4., 2., 4., 1., 2., 2., NA, 2., 4., 3., 3., 1.,
	2., 2., 3., 3., 2., 4., 2., 3., 4., 2., 2., 4., 2., 3., 2., 2., 3.,
	4., 2., 2., 4., 3., 3., 4., 3., 3., NA, 1., 1., 1., 4., 3., 1., 1.,
	4., 2., 3., 3., 3., 4., 2., 3., 4., 4., 4., 2., 4., 2., 2., 2., 3.,
	4., 2., 4., 4., 4., 3., 3., 3., 4., 4., 3., 4., 2., 2., 1., 2., 2.,
	2., 3., 3., 4., 3., 4., 4., 2., 4., 2., 2., 2., 4., 4., 3., 2., 1.,
	1., 1., 4., 1., 4., 2., 3., 2., 1., 2., 1., 2., 1., 4., 2., 4., 4.,
	2., 4., 4., 4., 4., 1., 2., 1., 2., NA, 3., 4., 1., 1., 2., NA, 2.,
	2., 4., 1., 2., 3., 3., 4., 1., 1., 2., 2., 3., 2., 2., 2., 4., 4.,
	2., 1., 2., 2., 4., 1., 4., 3., 1., 2., 3., 2., 1., 3., 2., 3., 4.,
	2., 4., 3., 3., 3., 3., 2., 2., 4., 3., NA, 3., 3., 4., 4., 4., 4.,
	3., 4., 4., 4., 1., 1., 3., 3., 2., 4., 4., 2., 2., 2., 3., 4., 2.,
	3., 1., 3., 1., 2., 2., 1., 4., 2., 2., 4., 3., 4., 3., 3., 4., 3.,
	2., 2., 4., 4., 4., 3., 1., 2., 1., 2., 3., 2., 2., 1., 1., 1., 2.,
	4., 3., 4., 3., 3., 3., 2., 4., 2., 2., NA, 3., 4., 1., 1., 4., 3.,
	3., 1., 2., 2., 4., NA, 3., 4., 2., 3., 1., 4., 4., 2., 1., 1., 2.,
	1., 1., 4., 3., 4., 2., 4., 1., 4., 2., 2., 3., 2., 2., 4., 2., 3.,
	2., 2., 2., 4., 4., 1., 4., 4., 2., 1., 4., 4., 4., 3., 2., 3., 3.,
	3., 3., 3., 4., 2., 2., 2., 4., 4., 4., 2., 1., 3., 4., 2., 1., 3.,
	2., 3., 1., 1., 1., 4., 4., 3., 2., 2., 2., 2., 1., 3., 1., 1., 1.,
	2., 3., 4., 2., 3., 2., 1., 4., 4., 4., 4., 2., 2., 1., NA, 4., 4.,
	3., 4., NA, 2., 2., 3., 3., 4., 2., 1., 1., 1., 2., 1., 1., 2., 4.,
	4., 4., 4., 2., 2., 2., 1., 1., 2., 3., 3., 4., 1., 2., 2., 2., 2.,
	4., 3., 3., 2., 2., 2., 3., 3., 3., 4., 4., 3., 4., 4., 3., 1., 1.,
	1., 2., 4., 4., 4., 2., 3., 2., 4., 3., 2., 2., 2., 2., 1., 4., 4.,
	2., NA, 4., 1., 1., 2., 2., 2., 2., 4., 4., 3., 3., 3., 4., 3., 4.,
	3., 2., 3., 4., 1., 2., 2., 1., 2., 1., 1., 4., 3., 3., 3., 3., 2.,
	3., 4., 1., 4., 2., 1., 1., 2., 1., 3., 4., 2., 4., 2., 1., 4., 1.,
	1., 1., 4., 2., 2., 3., 2., 2., 4., 1., 1., 4., 4., 2., 1., 3., 2.,
	3., 3., 2., 4., 4., 2., 4., 1., 3., 1., 2., 2., 3., 3., 3., 2., 4.,
	2., 2., 3., 3., 3., 3., 2., 2., 2., 2., 2., 2., 1., 4., 1., 4., 4.,
	4., NA, 4., 1., 4., 4., 2., 4., 2., NA, 1., 4., 3., 3., 4., 3., 4.,
	4., 3., 3., 3., 3., 3., 2., 2., 1., 4., 2., 2., 4., 2., 2., 3., 4.,
	3., 4., 4., 4., 4., 4., 4., 1., 1., 1., 3., 3., 4., 4., 1., 4., 2.,
	4., 2., 1., 1., 3., 4., 3., 4., 2., 2., 4., 3., 2., 2., 4., 2., 2.,
	1., 2., 3., 4., 1., 1., 1., 2., 1., 4., 3., 4., 1., 1., 3., 2., 2.,
	2., 2., 2., 3., 4., 4., 4., 4., 4., 4., 2., 2., 2., 4., 2., 2., 4.,
	2., 2., 2., 4., 1., 2., 1., 4., 2., 1., 4., 4., 1., 1., 4., 1., 1.,
	4., 3., 1., 4., 4., 4., 4., 4., 1., 3., 2., 2., 3., 4., 2., 2., 3.,
	1., 2., 2., 1., 4., 1., 2., 4., 1., 4., 4., NA, 3., 4., 2., 4., 4.,
	1., 4., 2., 2., 2., 3., 2., 3., 4., 3., 1., 4., 3., 4., 2., 2., 1.,
	1., 1., 4., 4., 3., 3., 3., 3., 4., 4., 4., 1., 4., 4., 2., 3., 4.,
	3., 2., 2., 2., NA, 1., 1., 3., 4., 3., 1., 1., 1., 1., NA, NA, 2.,
	2., 1., 3., 4., 4., 3., 1., 2., 4., 2., 2., 1., 1., 3., 2., 2., 2.,
	3., 1., 1., 4., 2., 2., 2., 1., 1., 3., 2., 4., 4., 2., 1., 4., 3.,
	1., 1., 3., 2., 4., 4., 2., 3., 3., 2., 2., 3., 3., 4., 2., 1., 2.,
	2., 4., 1., 1., 1., 3., 3., 4., 2., 2., 1., 4., 3., 3., 4., 4., 1.,
	4., 3., 4., 3., 2., 2., 3., 4., 2., 4., 1., 4., 1., 4., 3., 3., 3.,
	2., 3., 2., 4., 2., 4., 2., 1., 1., 2., 1., 4., 2., 4., 2., 2., 2.,
	1., 1., 2., 3., 2., 4., 1., 4., 1., 4., 4., 4., 4., 4., 3., 3., 3.,
	3., 2., 3., 4., 4., 4., 4., 2., 2., 3., 4., 1., 4., 3., 2., 2., 2.,
	2., 1., 1., 1., 2., 3., 4., 1., 1., 2., 2., 1., 1., 2., 2., 2., 3.,
	2., 3., 1., 2., 1., 4., 1., 2., 2., 4., 4., 4., 2., 4., 1., 1., 2.,
	4., 3., 2., 2., 2., 1., 2., 1., 1., 3., 4., 2., 1., 3., 3., NA, NA,
	4., 4., 2., 1., 4., 3., 4., 4., 4., 4., 2., 3., 2., 4., 3., 2., 3.,
	4., 2., 4., 2., 1., 2., 4., 1., 2., 2., 1., 2., 3., 2., 4., 4., 3.,
	4., 2., 2., 2., 2., 2., 4., 1., 2., 4., 4., 1., 4., 4., 1., 4., 1.,
	4., 4., 4., 4., 3., 3., 2., 1., 1., 3., 3., 2., 2., 4., 3., 4., 1.,
	4., 1., 4., 4., 3., 1., 1., 1., 2., 4., 3., 3., 1., 1., 4., 4., 2.,
	4., 1., 3., 4., 3., 3., 2., 2., 2., 2., 1., 2., 1., 1., 2., 4., 4.,
	2., 1., 2., 2., 4., 2., 4., 3., 3., 4., 2., 2., 2., 4., 1., 4., 3.,
	3., 2., 4., 1., 1., 3., 3., 2., 1., 4., 1., 3., 4., 4., 2., 1., 1.,
	2., 1., 3., 4., 2., 4., 4., 1., 3., 4., 3., 1., 4., 2., 1., 2., 1.,
	2., 3., 3., 2., 1., 4., 4., 2., 4., 2., 2., 1., 2., 4., 1., 2., 4.,
	1., 4., 2., 2., 3., 4., 1., 4., 3., 2., 4., 2., 3., 3., 2., 4., 2.,
	3., 1., 1., 2., 2., 3., 4., 2., 4., 1., 1., 1., 3., 3., 4., 2., 3.,
	1., 1., 1., 1., 2., 2., 2., 1., 2., 1., 2., 2., 2., 4., 3., 3., 4.,
	3., 2., 3., 2., 2., 2., 2., 2., 4., 4., 4., 4., 1., 3., 4., 4., 4.,
	3., 4., 3., NA, 3., 3., 4., 3., 3., 4., 3., 2., 1., 4., 4., 4., 4.,
	2., 3., 4., 4., 1., 2., 4., 4., 2., 3., 1., 2., 2., 1., 2., 3., 4.,
	2., 4., 3., 1., 2., 4., 2., 4., 1., 1., 4., 2., 2., 2., 4., 2., 1.,
	3., 1., 2., 4., 1., 1., 4., 2., 2., 4., 4., 4., 1., 2., 2., 2., 1.,
	2., 1., 1., 1., 4., 2., 4., 3., 2., 2., 4., 4., 1., 4., 4., 4., 4.,
	1., 4., 4., 4., 4., NA, 3., 1., 2., 1., 1., 4., 1., 1., 2., 2., 4.,
	NA, 3., 2., 4., 1., 4., 4., 2., 1., 3., 2., 2., NA, NA, 4., 1., 2.,
	3., 4., 2., 2., 4., 2., 2., 3., 3., 1., 1., 1., 1., 4., 4., 2., 4.,
	1., 2., 4., 2., 3., 2., 3., 3., 2., 2., 1., 4., 2., 2., 4., 3., 4.,
	NA, 3., 4., 4., 4., 4., 4., 3., 3., 1., 2., 4., 1., 2., 4., 1., 2.,
	1., 4., 4., 2., 4., 2., 3., 2., 2., 3., 2., 2., 2., 1., 3., 3., 4.,
	2., 3., 2., 4., 1., 1., 1., 4., 4., 2., 1., 3., 3., 2., 1., NA, 4.,
	4., 2., 1., 4., 4., 2., 4., 3., 3., 4., 2., 3., 4., 2., 2., 4., 3.,
	2., 1., 1., 1., 2., 1., 1., 4., 4., 4., 4., 1., 2., 4., 4., 4., 4.,
	3., 3., 4., 2., 2., 2., 1., 3., 2., 3., 4., 3., 2., 2., 1., 2., 3.,
	3., 4., 2., 4., 1., 4., 2., 4., 2., 4., 2., 4., 2., 2., 4., 3., 3.,
	3., 4., 3., 3., 2., 2., 2., 4., 4., 4., 2., 2., 1., 2., 1., 4., 3.,
	2., 3., 3., 1., 3., 4., 1., 4., 2., 2., 2., 4., 4., 3., 3., 2., 1.,
	4., 4., 4., 4., 4., 3., NA, 2., 3., 3., 3., 2., 4., NA, 3., 2., 4.,
	2., 4., 2., 4., 4., 4., 2., 4., 3., 1., 4., 3., 1., 2., 2., 2., 4.,
	4., 4., 4., 3., 4., 1., 4., 4., 4., 4., 4., 4., 2., 3., 4., 4., 2.,
	1., 4., 1., 4., 4., 2., 1., 1., 1., 4., 3., 4., 4., 3., 3., 3., 3.,
	3., 2., NA, 4., 2., 1., 1., 1., NA, 4., 1., 1., 3., 3., 3., 4., 2.,
	2., 2., 1., 1., 2., 4., 3., 3., 4., 2., 4., 1., 2., 2., 2., 4., 3.,
	2., 2., 2., 4., 1., 3., 4., 4., 4., 2., 3., 4., 4., 4., 4., 4., 2.,
	2., 1., 2., 2., NA, 1., 4., 1., 1., 1., 1., 4., 4., 4., 1., 4., 1.,
	2., 1., 2., 2., 3., 4., 1., 4., 3., 1., 1., 4., 4., 4., 4., 4., 1.,
	4., 4., 4., 1., 1., 4., 4., 1., 3., 2., 1., 4., 2., 2., 2., 3., 3.,
	4., 2., 1., 1., 4., 4., 4., 4., 2., 2., 2., 1., 1., 2., 3., 2., 2.,
	1., 4., 4., 3., 3., 3., 1., 1., 2., 2., 2., 4., 4., 3., 2., 3., 3.,
	4., 2., 3., 4., 2., 4., 2., 2., 4., 4., 1., 4., 4., 4., 4., 4., 4.,
	3., 2., 2., 2., 1., 2., 3., 2., 2., 3., 3., 3., 3., 1., 3., 1., 3.,
	2., 3., 1., 3., 3., 4., 4., 3., 2., 1., 2., 2., 1., 4., 3., 2., 2.,
	3., 4., 2., 2., 2., 3., 4., 2., 2., 4., 1., 4., 2., 2., 4., 2., NA,
	3., 4., 4., 1., 4., 2., 1., 4., 1., 4., 4., 4., 4., 4., 4., 2., 4.,
	4., 4., 2., 2., 4., 4., 2., 4., 3., 4., 4., 4., 2., 3., 4., 2., 4.,
	NA, NA, 4., 3., 3., 3., 2., 4., 2., 1., 2., 2., 2., 4., 4., 2., 2.,
	2., 4., 2., 4., 4., 3., 2., 4., 3., 2., 1., 4., 4., 2., 2., 2., 4.,
	2., 2., 3., 4., 1., 4., 4., 4., 3., 3., 3., 2., 2., 2., 1., 3., 3.,
	3., 2., 2., 4., 1., 3., 1., 2., 4., 4., 4., 2., 2., 1., 4., 2., 3.,
	2., 4., 3., 4., 2., 2., 2., 4., 4., 2., 3., 3., 2., 1., 1., 1., 1.,
	1., 1., 3., 4., 2., 4., 2., 1., 4., 1., 3., 4., 4., 2., 2., 4., 3.,
	2., 2., 2., 2., 1., 2., 4., 3., 4., 4., 4., 4., 3., 2., 2., 2., 2.,
	4., 4., 2., 2., 3., 2., 3., 3., NA, 3., 4., 4., 4., 4., 1., 2., 4.,
	2., 3., 4., 2., 2., 3., 2., 2., 3., 3., 2., 2., 3., 3., 1., 4., 1.,
	4., 2., 3., 2., 2., 1., 2., 2., 3., 3., 3., 4., 4., 4., 3., 2., 1.,
	2., 4., 3., 2., 2., 2., 2., 4., 3., 4., 2., 2., 4., 1., 1., 3., 2.,
	2., 2., 3., 2., 4., 2., 2., 4., 2., 4., 2., 2., 2., 3., 1., 3., 3.,
	1., 1., 4., 4., 2., 1., 2., 2., 2., 3., 4., 3., 2., 1., 3., 2., 2.,
	2., 3., 4., 4., 2., 3., 2., 3., 3., 1., 4., 4., 4., 4., 1., 4., 1.,
	1., 4., 2., 4., 3., 4., 4., 2., 4., 2., 1., 3., 3., 3., 1., 1., 1.,
	1., 4., 4., 4., 3., 2., 4., 2., 2., 1., 4., 4., 2., 3., 4., 4., 4.,
	3., 1., 3., 4., 4., 3., 2., 3., 4., 4., 4., 4., 1., 1., 2., 4., 1.,
	2., 2., 1., 4., 4., 4., 3., 4., 4., 4., 4., 2., 4., 2., 2., 3., 3.,
	2., 2., 1., 4., 3., 2., 3., 3., NA, 4., 2., 4., 2., 3., 2., 3., 3.,
	1., 4., 2., 4., 1., 3., 3., 2., 3., 2., 2., 1., 1., 1., 2., 3., 1.,
	1., 1., 3., 3., 2., 3., 4., 2., 2., 4., 4., 2., 4., 3., 2., 1., 2.,
	1., 4., 1., 3., 2., 2., 4., 4., 3., 2., 2., 2., 3., 4., 4., 2., 3.,
	3., 4., 4., 1., 4., 2., 4., 3., 2., 3., 2., 2., 3., 4., 4., 4., 3.,
	3., 3., 4., 4., 1., 2., 2., 4., 3., 3., 4., 2., 1., 1., 2., 1., 1.,
	3., 3., 4., 4., 3., 2., 4., NA, 3., 2., 4., 2., 2., 4., 4., 2., 4.,
	4., 3., 3., 1., 4., 3., 4., 4., 1., 3., 3., NA, 1., 2., 2., 2., 4.,
	3., 3., 2., 1., 1., 3., 4., 1., 4., 3., 1., 2., 2., 1., 4., 4., 4.,
	3., 3., 2., 4., 1., 2., 2., 2., 1., 2., 1., 1., 4., 4., 2., 3., 3.,
	1., 2., 2., 2., 2., 2., 1., 4., 4., 3., 2., 3., 1., 2., 4., 2., 3.,
	2., 2., 4., 4., 4., 2., 2., 2., 3., 3., 3., 4., 2., 3., 2., 1., 2.,
	2., 3., 1., 2., 2., 2., 2., 4., 4., 2., 3., 2., 2., 4., 1., 2., 2.,
	2., 2., 2., 2., 1., 1., 1., 2., 2., 3., 3., 4., 2., 4., 2., 3., 4.,
	2., 2., 2., 2., 3., 3., 2., 2., 2., 1., 1., 3., 3., 3., 4., 3., 4.,
	2., 2., 1., 4., 4., 2., 4., 2., 4., 2., 2., 3., 4., 2., 4., 3., 3.,
	4., 1., 1., 2., 3., 1., 1., 2., 2., 1., 4., 4., 4., 4., 3., 3., 2.,
	1., 1., 4., 4., 4., 1., 2., 4., 1., 4., 1., 2., 2., 2., 2., 3., 2.,
	1., 4., 4., 2., 2., 2., 1., 1., 4., NA, 4., 2., 2., 1., 3., 3., 2.,
	4., 4., 4., 4., 4., 3., 3., 2., 2., 2., 3., 2., 1., 4., 2., 4., 4.,
	4., 1., 2., 3., 3., 4., 2., 2., 4., 2., 2., 2., 2., NA, 4., 3., 4.,
	2., 3., 3., 4., 3., 4., 4., 4., 4., 2., 3., 1., 2., 2., 2., 2., 4.,
	3., 4., NA, 3., 2., 4., 3., 4., 3., 4., 2., 2., 4., 4., 4., 3., 4.,
	1., 4., 2., 2., 2., 4., 4., 4., 2., 2., 2., 3., 4., 4., 4., 4., 3.,
	3., 2., 2., 3., 2., 2., 2., 4., 3., 2., 2., 1., 1., 1., 1., 4., 1.,
	3., 4., 2., 4., 2., 2., 4., 1., 2., 2., 3., 4., 4., 1., 2., 2., 4.,
	2., 3., 2., 3., 1., 4., 3., 2., 4., 3., 3., 4., 4., 4., 4., 2., 2.,
	4., 3., 4., 1., 1., 2., 2., 2., 4., 2., 4., 4., 2., 1., 4., 1., 3.,
	2., 4., 4., 4., 4., 4., 1., 4., 4., 2., 4., 4., 2., 4., 2., 1., 4.,
	4., 4., 1., 1., 1., 2., 2., 2., 4., 3., 2., 1., 4., 1., 4., 3., 2.,
	3., 3., 2., 4., 2., 2., 3., 3., 1., 3., 1., 1., 2., 2., 1., 2., 2.,
	2., 2., 1., 4., 4., 2., 4., 2., 2., 3., 1., 3., 2., 4., 4., 4., 4.,
	1., 4., 2., 2., 2., 4., 4., 1., 4., 2., 4., 4., 4., 4., 3., 3., 3.,
	3., 4., 2., 2., 1., 1., 2., 3., 3., 4., 1., 1., 4., 3., 3., 4., 3.,
	3., 4., 1., NA, 4., 1., 1., 4., 3., 4., 3., 3., 1., 2., 1., 2., 1.,
	4., 4., 3., 4., 4., 4., 2., 2., 1., 3., 3., 4., 1., 4., 2., 1., 2.,
	4., 3., 2., 4., 4., 3., 3., 3., 2., NA, 2., 2., 4., 2., 4., 3., 3.,
	3., 3., 2., 3., 2., 2., 1., 3., 2., 3., 2., 4., 3., 3., 2., 1., 2.,
	1., 2., NA, 3., 3., 4., 4., 3., 3., 2., 4., 2., 4., 2., 3., 3., 1.,
	4., 3., 2., 3., 2., 2., 3., 3., 3., 4., 3., NA, 4., 3., 3., 3., 3.,
	3., 4., 4., 4., 3., 3., 3., 1., 1., 4., 4., 1., 1., 4., 3., 4., 4.,
	1., 1., 1., 1., 2., 4., 2., 4., 4., 3., 3., 2., 2., 3., 2., 2., 2.,
	3., 3., 4., 2., 2., 2., 4., 4., 3., 2., 2., 2., 3., 2., 2., 4., 2.,
	4., 3., 2., 4., 4., 1., 4., 3., 4., 1., 4., 2., 1., 3., 2., 3., 2.,
	2., 3., 4., 4., 2., 4., 1., 1., 4., 2., 4., 3., 2., 2., 4., 1., 1.,
	2., 4., 4., 4., 4., 2., 4., 4., 4., 3., 1., 2., 3., 3., 1., 2., 2.,
	3., 3., 3., 3., 2., 2., 2., 3., 2., 2., 2., 1., 1., 1., 2., 4., 3.,
	3., 4., 1., 1., 1., 1., 3., 3., 3., 2., 3., 1., 3., 2., 2., 2., 4.,
	3., 1., 4., 2., 2., 1., 4., 2., 4., 2., 4., 2., 2., 2., 4., 3., 2.,
	1., 3., 4., 2., 2., 2., 2., 4., 4., 1., 3., 2., 2., 4., NA, 2., 4.,
	4., 4., 2., 4., 1., 4., 3., 2., 2., 2., 3., 3., 2., 3., 2., 1., 1.,
	2., 2., 3., 3., 4., 3., 4., 4., 3., 2., 3., 2., 3., 4., 1., 2., 4.,
	4., 2., 3., 3., 2., 3., 2., 3., 3., 3., 3., 4., 3., 3., 2., 2., 2.,
	1., 4., 1., 2., 2., 4., 4., 1., 2., 2., 3., 2., 2., 4., 1., 4., 2.,
	1., 2., 2., 2., 4., 4., 4., 3., 4., 3., 1., 2., 2., 2., 1., 1., 4.,
	1., 2., 2., 1., 1., 2., 4., 4., 2., 3., 3., NA, 3., 4., 2., 2., 2.,
	1., 2., 4., 1., 1., 4., 2., 4., 1., 2., 2., 1., 3., 4., 2., 1., 3.,
	4., 3., 1., 2., 2., 2., 2., 3., 1., 4., 1., 4., 2., 4., 3., 4., 4.,
	3., 2., 3., 2., 4., 4., 4., 4., 3., 4., 4., 2., 2., 1., 1., 3., 3.,
	2., 2., 4., 3., 1., 1., 4., 2., 4., 2., 4., 4., 4., 1., 1., 4., 1.,
	2., 4., 2., 4., 2., 3., 1., 1., 1., 1., 3., 4., 4., 2., 4., 4., 3.,
	3., 2., 3., 2., 1., 2., 3., 4., 1., 1., 1., 2., 2., 4., 4., 3., 2.,
	4., 2., 1., 4., 1., 4., 4., 3., 4., 4., 4., 4., 1., 4., 2., 4., 4.,
	4., 3., 3., 4., 2., 2., 3., 3., 2., 3., 3., 2., 4., 2., 2., 4., 4.,
	3., 4., 2., 2., 2., 3., 2., 4., 2., 2., 4., 2., 2., 2., 3., 3., 1.,
	2., 3., 2., 4., 3., 4., 2., 2., 1., 1., 4., 4., 4., 4., 4., 1., 4.,
	4., 2., 3., 1., 3., 2., 4., 1., 4., 2., 3., 3., 4., NA, 1., 4., 3.,
	4., 4., 3., 4., 4., 2., 2., 4., 1., 4., 3., 3., 4., 4., 4., 4., 2.,
	2., 2., 1., 1., 1., 4., 4., 4., 3., 3., 3., 1., 1., 1., 2., 3., 1.,
	1., 4., 4., 2., 2., 1., 4., 4., 1., 1., 1., 2., 2., 3., 3., 4., 1.,
	3., 2., 2., 1., 4., 3., 4., 4., 4., 4., 2., 4., 3., 2., 2., 1., 4.,
	2., 4., 4., 4., 2., 2., 4., 3., 2., 4., 1., 4., 4., 4., 4., 4., 4.,
	4., 3., 2., 2., 1., 4., 4., 2., 3., 2., 1., 1., 4., 3., 4., 4., 4.,
	3., 2., NA, 2., 3., 4., 3., 2., 3., 3., 4., 1., 2., 2., 4., 4., 1.,
	4., 1., 3., 3., 2., 2., 3., 1., 4., 3., 2., 2., 4., 4., 2., 2., 2.,
	2., 1., 2., 2., 1., 1., 4., 4., 4., 2., 2., 2., 4., 2., 3., 3., 4.,
	4., 2., 3., 3., 1., 2., 3., 4., 2., 4., 4., 3., 1., 2., 1., 2., 4.,
	1., 1., 2., 2., 2., 3., 3., 2., 3., 1., 2., 3., 4., 3., 4., 3., 2.,
	3., 2., 2., 4., 2., 3., 4., 4., 2., 2., 3., 2., 4., 3., 2., 2., 4.,
	3., 3., 4., 1., 4., 1., 4., 4., 2., 2., 2., 3., 2., 4., 4., 3., 1.,
	3., 2., 1., 1., 3., 4., 3., 1., 1., 4., 4., 4., 4., 2., 3., 2., 3.,
	3., 4., 4., 4., 3., 4., 3., 2., 2., 3., 2., 2., 4., 1., 4., 2., 4.,
	2., 4., 4., 4., 2., 3., 3., 2., 2., 4., 2., 4., 4., 1., 4., 1., 1.,
	3., 2., 1., 3., 2., 2., 2., 2., 2., 2., 2., 2., 1., 2., 3., 1., 4.,
	2., 3., 4., 4., 4., 4., 1., 1., 2., 4., 2., 2., 4., 1., 3., 4., 3.,
	4., 4., 2., 1., 4., 4., 4., 2., 2., 2., 4., 1., 1., 1., 1., 1., 4.,
	3., 2., 4., 3., 4., 4., 3., 3., 4., 4., 4., 4., 2., 2., 3., 4., 2.,
	4., 4., 3., 2., 3., 4., 4., NA, 3., 1., 4., 1., 2., 4., 4., 4., 2.,
	2., 1., 1., 3., 3., 3., 3.),
	.Dim = c(1941, 3)
	),
	g = structure(
	.Data=
	c(3., 2., 1., 2., 3., 1., 2., 3., 4., 3., 1., 2., 4., 1., 2.,
	2., 1., 4., 1.,
	2., 4., 3., 4., 1., 4., 2., 3., 2., 3., 4., 1., 2., 4., 4., 2., 1.,
	4., 1., 3., 3., 2., 4., 4., 1., 3., 2., 3., 1., 4., 2., 1., 3., 2.,
	4., 2., 3., 4., 4., 3., 1., 4., 1., 3., 4., 3., 2., 2., 1., 4., 2.,
	4., 1., 4., 2., 3., 3., 1., 4., 2., 1., 3., 2., 3., 4., 3., 4., 1.,
	3., 4., 1., 3., 2., 4., 2., 1., 4., 3., 1., 4., 4., 1., 2., 2., 1.,
	4., 2., 3., 1., 4., 3., 2., 4., 2., 3., 2., 4., 1., 3., 2., 4., 2.,
	1., 4., 2., 3., 1., 3., 4., 2., 3., 2., 1., 2., 1., 4., 1., 4., 3.,
	3., 1., 4., 3., 1., 2., 2., 3., 1., 2., 4., 1., 2., 1., 4., 2., 1.,
	3., 4., 2., 3., 3., 1., 4., 2., 3., 1., 1., 4., 3., 4., 1., 3., 3.,
	4., 2., 4., 3., 1., 4., 3., 1., 3., 1., 4., 4., 3., 1., 3., 4., 1.,
	2., 4., 3., 4., 1., 3., 2., 4., 1., 4., 3., 1., 2., 3., 1., 2., 1.,
	4., 2., 3., 4., 2., 4., 3., 3., 4., 1., 2., 1., 3., 2., 4., 1., 2.,
	4., 3., 4., 2., 3., 1., 3., 2., 4., 2., 1., 3., 4., 2., 3., 4., 1.,
	4., 3., 2., 2., 4., 3., 4., 2., 3., 2., 3., 4., 2., 3., 4., 3., 4.,
	2., 3., 1., 2., 3., 1., 4., 2., 3., 1., 3., 1., 2., 3., 2., 4., 2.,
	4., 1., 2., 1., 3., 4., 3., 2., 4., 3., 1., 2., 3., 4., 4., 3., 2.,
	2., 1., 4., 3., 2., 1., 4., 2., 3., 4., 3., 2., 4., 1., 3., 1., 2.,
	4., 3., 2., 1., 4., 3., 1., 3., 4., 1., 4., 2., 3., 4., 2., 3., 4.,
	1., 2., 4., 2., 1., 2., 1., 3., 3., 1., 4., 2., 3., 4., 4., 2., 3.,
	3., 1., 2., 4., 2., 1., 2., 3., 4., 4., 3., 1., 4., 1., 2., 2., 1.,
	3., 4., 3., 1., 4., 3., 1., 4., 2., 3., 2., 3., 1., 4., 3., 1., 2.,
	4., 1., 4., 3., 2., 2., 4., 3., 4., 1., 2., 4., 2., 3., 2., 1., 4.,
	1., 4., 2., 3., 4., 2., 4., 2., 1., 2., 4., 1., 4., 3., 1., 2., 1.,
	4., 4., 2., 1., 2., 3., 4., 4., 2., 1., 2., 1., 3., 4., 3., 1., 4.,
	2., 3., 2., 3., 4., 3., 4., 1., 2., 3., 4., 2., 4., 3., 2., 1., 3.,
	2., 3., 1., 3., 2., 1., 4., 3., 2., 4., 3., 1., 3., 4., 1., 4., 1.,
	3., 2., 3., 4., 4., 2., 1., 2., 4., 3., 4., 3., 1., 4., 3., 2., 4.,
	2., 1., 4., 1., 3., 4., 2., 1., 4., 1., 3., 4., 1., 3., 3., 2., 1.,
	3., 2., 4., 1., 4., 2., 2., 3., 1., 2., 1., 4., 4., 2., 3., 4., 3.,
	1., 4., 1., 3., 3., 1., 4., 3., 2., 4., 4., 1., 2., 4., 2., 3., 4.,
	2., 1., 4., 2., 3., 4., 3., 1., 2., 1., 4., 2., 3., 1., 3., 4., 1.,
	4., 2., 1., 4., 3., 2., 2., 4., 1., 4., 1., 2., 3., 2., 4., 4., 2.,
	3., 4., 1., 2., 4., 1., 2., 3., 1., 4., 2., 1., 4., 4., 3., 2., 3.,
	1., 4., 3., 1., 4., 3., 4., 1., 4., 1., 3., 3., 1., 4., 4., 3., 2.,
	2., 4., 1., 2., 1., 4., 4., 3., 2., 3., 2., 1., 2., 3., 4., 4., 1.,
	2., 2., 1., 3., 1., 4., 3., 2., 1., 4., 4., 1., 2., 4., 2., 3., 4.,
	3., 1., 2., 1., 3., 2., 3., 1., 4., 3., 1., 3., 4., 1., 4., 1., 2.,
	3., 2., 4., 3., 4., 1., 4., 2., 1., 3., 4., 1., 2., 1., 4., 2., 1.,
	4., 4., 1., 3., 3., 2., 4., 2., 4., 3., 4., 2., 1., 3., 1., 2., 4.,
	2., 1., 4., 3., 1., 3., 2., 4., 3., 2., 4., 4., 1., 3., 2., 4., 3.,
	4., 3., 1., 2., 4., 3., 4., 2., 1., 2., 3., 1., 2., 3., 1., 3., 2.,
	4., 2., 1., 3., 3., 2., 1., 4., 3., 2., 2., 3., 4., 2., 3., 4., 1.,
	3., 4., 2., 3., 4., 3., 4., 1., 2., 3., 4., 3., 1., 4., 2., 4., 1.,
	3., 4., 2., 3., 1., 2., 2., 1., 3., 4., 1., 3., 2., 4., 3., 2., 3.,
	4., 3., 4., 1., 2., 4., 3., 4., 2., 3., 2., 3., 1., 3., 1., 2., 3.,
	4., 1., 2., 1., 3., 2., 4., 3., 2., 4., 3., 2., 3., 1., 1., 4., 2.,
	4., 3., 1., 4., 2., 1., 4., 1., 3., 4., 1., 3., 4., 2., 3., 4., 1.,
	3., 3., 1., 2., 2., 3., 1., 3., 4., 2., 3., 2., 4., 3., 2., 4., 2.,
	4., 1., 4., 1., 3., 4., 1., 2., 4., 3., 2., 1., 4., 2., 2., 1., 3.,
	3., 1., 2., 3., 1., 2., 4., 2., 1., 4., 2., 3., 4., 2., 1., 2., 3.,
	4., 2., 3., 4., 4., 1., 2., 3., 2., 1., 3., 1., 4., 4., 1., 2., 3.,
	2., 1., 3., 1., 4., 4., 1., 3., 4., 2., 3., 4., 3., 2., 4., 1., 2.,
	4., 2., 1., 3., 2., 4., 4., 1., 3., 2., 1., 4., 2., 4., 1., 2., 4.,
	1., 4., 1., 2., 4., 1., 3., 2., 4., 3., 4., 3., 2., 1., 2., 4., 2.,
	4., 1., 3., 2., 1., 3., 2., 1., 4., 1., 3., 4., 2., 1., 4., 3., 1.,
	2., 1., 3., 4., 3., 1., 3., 2., 4., 4., 1., 2., 4., 3., 2., 4., 2.,
	1., 4., 2., 3., 4., 2., 3., 4., 2., 1., 2., 4., 3., 3., 2., 4., 4.,
	3., 1., 4., 1., 2., 2., 4., 1., 4., 3., 2., 2., 4., 3., 4., 2., 1.,
	2., 4., 3., 3., 2., 1., 3., 1., 2., 4., 3., 2., 4., 3., 1., 4., 3.,
	1., 2., 3., 1., 2., 4., 3., 4., 2., 1., 4., 2., 3., 4., 1., 3., 4.,
	3., 1., 2., 3., 4., 2., 1., 3., 4., 2., 3., 3., 1., 4., 4., 1., 2.,
	3., 2., 1., 3., 1., 2., 2., 4., 3., 3., 1., 2., 4., 1., 2., 4., 3.,
	1., 3., 1., 4., 2., 1., 4., 3., 2., 4., 4., 1., 3., 3., 1., 4., 4.,
	3., 2., 3., 1., 4., 2., 4., 3., 4., 2., 1., 3., 4., 1., 4., 1., 3.,
	3., 2., 1., 3., 4., 2., 2., 4., 1., 3., 2., 4., 4., 3., 2., 4., 3.,
	2., 3., 1., 2., 3., 4., 2., 3., 1., 4., 4., 1., 2., 1., 3., 2., 2.,
	3., 4., 4., 2., 1., 2., 4., 1., 2., 4., 1., 2., 3., 4., 2., 4., 1.,
	4., 3., 1., 4., 1., 2., 3., 4., 2., 4., 1., 3., 4., 1., 2., 4., 3.,
	1., 3., 1., 2., 4., 2., 1., 4., 3., 1., 2., 1., 4., 2., 4., 3., 4.,
	1., 3., 4., 3., 1., 2., 1., 3., 3., 4., 2., 2., 3., 4., 3., 1., 4.,
	4., 2., 1., 4., 1., 2., 2., 1., 3., 2., 4., 3., 1., 3., 2., 4., 2.,
	1., 3., 1., 2., 4., 2., 3., 4., 2., 3., 3., 4., 1., 3., 4., 1., 3.,
	2., 4., 3., 1., 4., 4., 1., 2., 3., 1., 2., 4., 2., 3., 3., 4., 1.,
	3., 2., 4., 4., 1., 2., 3., 2., 1., 3., 1., 2., 2., 1., 3., 4., 1.,
	3., 2., 4., 1., 4., 1., 2., 4., 1., 2., 4., 1., 2., 3., 1., 4., 3.,
	4., 2., 2., 3., 4., 4., 1., 2., 2., 4., 1., 4., 2., 3., 4., 3., 2.,
	2., 1., 3., 1., 2., 3., 2., 1., 4., 4., 1., 3., 3., 4., 2., 3., 2.,
	1., 2., 4., 3., 3., 2., 4., 4., 3., 1., 1., 4., 3., 2., 3., 1., 2.,
	1., 3., 4., 3., 1., 4., 3., 1., 4., 2., 1., 1., 3., 2., 2., 3., 4.,
	2., 3., 1., 2., 3., 4., 2., 1., 3., 4., 1., 3., 2., 1., 3., 2., 3.,
	1., 3., 2., 1., 2., 1., 3., 4., 2., 3., 3., 2., 1., 4., 2., 1., 3.,
	2., 1., 4., 3., 2., 3., 4., 1., 2., 4., 3., 4., 2., 1., 3., 2., 4.,
	1., 3., 4., 3., 1., 2., 4., 3., 1., 2., 4., 3., 1., 3., 2., 2., 4.,
	3., 2., 4., 3., 4., 1., 2., 4., 2., 3., 2., 1., 3., 4., 2., 3., 4.,
	2., 3., 4., 1., 3., 4., 1., 3., 3., 2., 1., 4., 3., 2., 4., 2., 1.,
	2., 1., 4., 4., 1., 2., 2., 3., 4., 4., 2., 3., 3., 4., 1., 2., 4.,
	3., 4., 1., 3., 2., 4., 3., 2., 1., 4., 3., 4., 2., 2., 3., 1., 3.,
	2., 4., 2., 1., 4., 2., 3., 4., 2., 4., 3., 3., 1., 2., 4., 1., 2.,
	3., 1., 2., 3., 4., 2., 3., 1., 2., 4., 2., 3., 2., 1., 3., 3., 2.,
	4., 2., 1., 3., 3., 4., 2., 1., 4., 2., 2., 3., 1., 4., 1., 2., 4.,
	1., 3., 3., 2., 4., 2., 4., 3., 3., 2., 1., 2., 4., 1., 2., 4., 3.,
	3., 1., 2., 2., 3., 1., 3., 1., 2., 4., 2., 1., 4., 1., 2., 4., 3.,
	1., 4., 1., 3., 2., 3., 1., 1., 2., 3., 4., 1., 2., 4., 2., 1., 2.,
	4., 3., 3., 2., 4., 2., 4., 3., 4., 2., 1., 4., 3., 1., 4., 2., 1.,
	2., 3., 4., 2., 4., 1., 3., 1., 4., 4., 1., 2., 2., 3., 1., 4., 2.,
	3., 4., 2., 3., 2., 3., 4., 4., 3., 2., 4., 2., 3., 4., 3., 2., 4.,
	1., 2., 2., 1., 4., 4., 1., 3., 1., 4., 2., 4., 3., 1., 4., 1., 3.,
	3., 4., 2., 3., 4., 2., 3., 1., 2., 4., 3., 1., 3., 4., 2., 4., 1.,
	3., 4., 2., 3., 3., 4., 2., 3., 1., 4., 4., 3., 1., 3., 1., 4., 4.,
	2., 1., 2., 1., 3., 3., 2., 4., 4., 3., 1., 4., 3., 1., 2., 1., 3.,
	4., 2., 3., 2., 4., 1., 4., 2., 3., 4., 3., 2., 2., 4., 1., 3., 1.,
	2., 3., 1., 4., 3., 2., 4., 2., 4., 3., 2., 3., 1., 2., 4., 3., 4.,
	2., 3., 4., 1., 2., 4., 2., 3., 2., 4., 3., 4., 1., 3., 4., 3., 2.,
	3., 1., 4., 4., 3., 2., 4., 1., 3., 4., 1., 2., 2., 1., 3., 4., 1.,
	2., 3., 4., 1., 3., 4., 2., 4., 3., 1., 2., 4., 3., 4., 2., 1., 3.,
	1., 4., 2., 1., 4., 4., 1., 2., 2., 3., 1., 4., 3., 1., 4., 1., 2.,
	3., 2., 1., 3., 1., 4., 3., 2., 1., 4., 2., 1., 2., 3., 1., 3., 2.,
	1., 2., 4., 3., 4., 1., 3., 3., 2., 4., 2., 4., 1., 2., 1., 3., 3.,
	2., 4., 4., 3., 1., 2., 1., 4., 3., 2., 1., 4., 3., 2., 3., 1., 2.,
	4., 2., 1., 2., 3., 1., 4., 1., 3., 4., 3., 2., 2., 4., 3., 2., 1.,
	4., 2., 4., 1., 2., 4., 1., 3., 4., 2., 2., 4., 3., 4., 1., 2., 3.,
	4., 1., 4., 1., 2., 4., 2., 3., 4., 2., 3., 4., 3., 2., 4., 2., 1.,
	3., 1., 2., 4., 3., 2., 4., 1., 2., 4., 2., 1., 4., 1., 3., 4., 2.,
	3., 3., 2., 1., 3., 4., 1., 4., 1., 3., 2., 3., 4., 1., 2., 4., 4.,
	2., 3., 4., 2., 1., 4., 2., 3., 3., 2., 4., 4., 3., 2., 2., 4., 1.,
	3., 4., 2., 4., 2., 3., 1., 3., 2., 2., 4., 3., 1., 2., 4., 2., 1.,
	3., 4., 2., 3., 4., 1., 2., 4., 1., 2., 4., 3., 2., 3., 1., 2., 4.,
	1., 2., 3., 4., 1., 2., 4., 1., 4., 1., 2., 2., 4., 3., 3., 2., 1.,
	4., 1., 2., 4., 3., 1., 4., 3., 1., 3., 2., 4., 1., 4., 2., 1., 3.,
	4., 2., 3., 1., 4., 1., 2., 2., 1., 4., 2., 4., 3., 1., 3., 2., 2.,
	4., 1., 3., 4., 2., 2., 4., 3., 3., 1., 4., 4., 1., 2., 4., 1., 3.,
	2., 3., 4., 2., 4., 1., 2., 1., 4., 2., 1., 4., 2., 3., 4., 4., 2.,
	3., 2., 4., 1., 4., 2., 3., 3., 2., 1., 4., 3., 1., 3., 1., 2., 4.,
	3., 2., 3., 4., 2., 4., 3., 2., 4., 1., 3., 3., 2., 4., 4., 2., 3.,
	2., 4., 3., 4., 1., 2., 3., 2., 1., 4., 3., 2., 4., 2., 3., 4., 2.,
	3., 4., 3., 2., 3., 4., 1., 4., 2., 1., 2., 1., 4., 2., 4., 1., 4.,
	2., 1., 4., 3., 1., 3., 2., 1., 2., 4., 3., 3., 1., 2., 3., 2., 4.,
	4., 1., 3., 4., 2., 1., 1., 2., 4., 1., 4., 2., 4., 3., 2., 4., 1.,
	3., 2., 3., 4., 4., 3., 1., 4., 1., 3., 3., 1., 4., 4., 3., 2., 4.,
	3., 2., 2., 4., 1., 3., 2., 4., 4., 3., 2., 4., 1., 3., 2., 3., 4.,
	4., 1., 2., 4., 2., 3., 4., 3., 1., 3., 1., 4., 4., 1., 3., 3., 2.,
	1., 2., 4., 1., 2., 3., 1., 2., 4., 1., 1., 2., 3., 2., 4., 3., 1.,
	4., 2., 4., 3., 1., 2., 1., 3., 3., 2., 4., 3., 1., 4., 2., 4., 3.,
	4., 2., 3., 3., 2., 1., 2., 1., 4., 1., 2., 4., 4., 2., 3., 4., 1.,
	2., 4., 2., 3., 3., 2., 4., 4., 2., 3., 3., 4., 1., 4., 2., 1., 2.,
	3., 4., 4., 3., 2., 4., 3., 2., 3., 2., 4., 4., 1., 3., 4., 2., 3.,
	4., 3., 2., 2., 3., 1., 2., 1., 3., 4., 3., 2., 2., 4., 1., 2., 4.,
	3., 4., 3., 1., 2., 1., 3., 2., 4., 1., 4., 2., 1., 2., 4., 3., 3.,
	2., 4., 4., 1., 3., 3., 2., 4., 4., 1., 2., 3., 1., 2., 4., 3., 2.,
	4., 2., 1., 4., 3., 1., 3., 4., 1., 4., 1., 2., 2., 4., 3., 2., 3.,
	1., 4., 2., 3., 4., 2., 1., 3., 1., 4., 2., 1., 4., 4., 1., 2., 3.,
	4., 1., 4., 3., 1., 2., 3., 4., 2., 4., 3., 4., 2., 3., 4., 2., 1.,
	4., 3., 2., 3., 2., 1., 2., 3., 1., 2., 3., 1., 4., 1., 3., 2., 1.,
	3., 1., 2., 4., 4., 3., 2., 3., 2., 1., 2., 1., 3., 4., 1., 3., 3.,
	4., 2., 3., 1., 4., 4., 2., 1., 1., 3., 2., 3., 4., 1., 4., 3., 1.,
	3., 1., 2., 4., 3., 1., 4., 3., 1., 4., 3., 2., 3., 1., 4., 3., 2.,
	1., 3., 1., 2., 3., 1., 2., 4., 1., 2., 4., 3., 1., 4., 2., 1., 4.,
	1., 2., 3., 2., 1., 2., 3., 4., 3., 4., 1., 2., 4., 3., 2., 4., 3.,
	2., 3., 1., 2., 3., 4., 3., 2., 1., 4., 2., 1., 3., 2., 4., 3., 2.,
	4., 2., 3., 1., 3., 2., 4., 1., 3., 2., 4., 2., 3., 2., 1., 4., 2.,
	4., 3., 4., 3., 2., 3., 4., 1., 4., 1., 3., 2., 1., 3., 4., 3., 2.,
	2., 4., 1., 4., 3., 1., 4., 1., 2., 4., 3., 2., 4., 1., 2., 4., 3.,
	2., 3., 1., 4., 4., 1., 2., 3., 2., 4., 2., 3., 1., 4., 3., 2., 3.,
	2., 4., 3., 1., 2., 3., 2., 4., 3., 4., 1., 3., 4., 1., 1., 2., 3.,
	4., 2., 1., 4., 1., 2., 4., 1., 2., 4., 2., 1., 2., 3., 1., 4., 3.,
	1., 4., 2., 3., 2., 4., 3., 4., 2., 3., 2., 3., 1., 4., 1., 3., 2.,
	3., 1., 2., 1., 4., 4., 1., 2., 4., 3., 2., 4., 1., 2., 2., 1., 3.,
	2., 1., 4., 2., 4., 1., 2., 4., 3., 4., 3., 1., 3., 2., 1., 4., 3.,
	1., 4., 1., 3., 3., 1., 4., 2., 4., 1., 4., 1., 3., 4., 2., 3., 4.,
	2., 3., 2., 1., 4., 2., 4., 1., 3., 1., 4., 2., 3., 4., 1., 3., 2.,
	2., 3., 4., 3., 1., 4., 4., 1., 2., 4., 3., 2., 4., 1., 2., 2., 3.,
	1., 2., 3., 4., 3., 2., 4., 4., 1., 2., 2., 3., 1., 3., 4., 2., 4.,
	3., 2., 2., 4., 3., 3., 4., 2., 2., 1., 4., 4., 1., 3., 4., 1., 3.,
	4., 3., 2., 4., 1., 2., 4., 2., 1., 3., 4., 1., 2., 3., 4., 2., 3.,
	1., 4., 1., 3., 4., 1., 3., 2., 1., 3., 2., 1., 3., 2., 1., 3., 4.,
	1., 2., 4., 1., 2., 3., 1., 4., 4., 1., 3., 2., 4., 1., 3., 4., 2.,
	4., 1., 2., 2., 1., 4., 4., 2., 1., 3., 2., 1., 2., 4., 1., 4., 1.,
	3., 2., 4., 1., 4., 3., 2., 3., 1., 4., 4., 1., 3., 4., 1., 2., 4.,
	2., 1., 4., 2., 1., 4., 1., 3., 4., 1., 2., 4., 2., 1., 4., 2., 3.,
	4., 1., 2., 4., 2., 1., 4., 3., 1., 4., 2., 1., 4., 3., 1., 2., 3.,
	4., 3., 2., 4., 3., 4., 1., 2., 1., 3., 3., 1., 2., 4., 1., 2., 2.,
	1., 3., 4., 1., 2., 2., 1., 3., 2., 3., 4., 2., 1., 4., 4., 2., 1.,
	2., 4., 3., 2., 1., 4., 4., 2., 3., 3., 2., 4., 4., 2., 1., 1., 2.,
	3., 2., 1., 4., 3., 4., 1., 2., 3., 1., 4., 1., 2., 4., 2., 3., 2.,
	1., 4., 4., 1., 2., 4., 1., 2., 3., 4., 1., 1., 4., 3., 4., 2., 1.,
	3., 4., 1., 2., 1., 4., 4., 1., 2., 4., 1., 3., 3., 2., 4., 2., 1.,
	4., 4., 1., 3., 3., 2., 1., 2., 3., 4., 1., 2., 4., 4., 2., 3., 2.,
	1., 3., 1., 2., 4., 3., 1., 2., 1., 3., 4., 4., 2., 3., 4., 3., 2.,
	4., 3., 2., 2., 4., 1., 4., 3., 2., 2., 4., 3., 4., 3., 2., 1., 3.,
	2., 4., 1., 3., 4., 2., 1., 2., 3., 1., 4., 3., 1., 2., 4., 1., 2.,
	4., 1., 4., 3., 1., 2., 4., 3., 4., 3., 2., 4., 1., 3., 4., 1., 3.,
	3., 4., 2., 3., 2., 1., 4., 3., 2., 2., 3., 1., 2., 3., 4., 2., 4.,
	1., 4., 1., 3., 4., 3., 2., 4., 1., 2., 3., 2., 4., 4., 2., 1., 4.,
	2., 1., 4., 3., 1., 4., 3., 1., 4., 3., 1., 2., 1., 3., 4., 2., 1.,
	2., 1., 4., 2., 4., 1., 2., 4., 1., 2., 3., 4., 4., 3., 2., 3., 1.,
	4., 3., 2., 4., 2., 4., 3., 1., 4., 2., 3., 4., 1., 3., 2., 4., 3.,
	2., 1., 3., 1., 4., 4., 2., 1., 4., 1., 2., 4., 2., 1., 2., 3., 1.,
	3., 4., 1., 4., 3., 1., 2., 4., 3., 4., 3., 1., 2., 3., 1., 2., 1.,
	3., 4., 1., 2., 4., 3., 2., 2., 4., 3., 2., 3., 4., 3., 1., 4., 4.,
	3., 1., 2., 3., 4., 3., 1., 4., 3., 4., 1., 2., 4., 1., 4., 2., 1.,
	3., 1., 2., 3., 4., 2., 3., 2., 1., 1., 4., 2., 4., 1., 2., 3., 2.,
	4., 4., 2., 3., 4., 3., 2., 2., 4., 1., 2., 4., 1., 4., 2., 3., 2.,
	1., 4., 2., 1., 4., 2., 1., 4., 4., 3., 1., 2., 3., 1., 4., 3., 1.,
	4., 1., 3., 4., 2., 3., 2., 1., 3., 3., 2., 4., 3., 4., 1., 4., 1.,
	2., 2., 1., 4., 4., 1., 2., 4., 3., 2., 2., 4., 3., 3., 1., 2., 1.,
	3., 2., 4., 2., 3., 3., 1., 4., 1., 3., 2., 4., 3., 2., 4., 2., 1.,
	2., 1., 4., 1., 2., 3., 3., 2., 4., 3., 1., 4., 4., 1., 3., 3., 4.,
	1., 2., 4., 1., 4., 3., 1., 3., 1., 4., 2., 1., 3., 3., 2., 1., 2.,
	4., 1., 3., 2., 1., 3., 4., 1., 4., 1., 3., 2., 1., 4., 4., 3., 2.,
	2., 1., 4., 3., 2., 4., 2., 3., 4., 3., 2., 4., 1., 3., 2., 3., 2.,
	1., 4., 2., 1., 4., 2., 3., 4., 1., 2., 4., 1., 2., 4., 1., 2., 4.,
	1., 2., 2., 4., 1., 3., 4., 2., 4., 1., 2., 2., 1., 4., 3., 4., 1.,
	4., 1., 2., 3., 1., 4., 4., 2., 3., 4., 3., 1., 4., 1., 3., 4., 3.,
	1., 4., 2., 3., 3., 4., 2., 3., 1., 4., 2., 3., 1., 4., 3., 2., 3.,
	1., 2., 3., 1., 2., 2., 1., 4., 1., 4., 2., 3., 1., 4., 2., 4., 3.,
	2., 3., 4., 2., 4., 3., 3., 2., 4., 2., 1., 4., 2., 1., 3., 3., 1.,
	4., 4., 3., 1., 2., 1., 4., 4., 2., 1., 3., 4., 1., 2., 4., 3., 2.,
	1., 3., 3., 1., 2., 4., 3., 2., 2., 1., 4., 3., 2., 1., 2., 4., 3.,
	4., 2., 3., 4., 3., 2., 4., 1., 2., 4., 1., 3., 4., 2., 3., 2., 4.,
	3., 3., 1., 4., 4., 1., 3., 2., 4., 3., 2., 4., 1., 2., 3., 1., 3.,
	2., 1., 4., 3., 1., 4., 1., 3., 1., 3., 4., 3., 1., 2., 4., 1., 3.,
	2., 3., 4., 3., 2., 1., 4., 2., 3., 3., 4., 2., 2., 4., 1., 4., 2.,
	1., 1., 2., 3., 3., 4., 2., 4., 2., 3., 2., 1., 4., 4., 3., 2., 3.,
	1., 2., 3., 4., 1., 4., 1., 2., 4., 1., 2., 4., 2., 3., 4., 1., 3.,
	2., 3., 1., 2., 4., 3., 4., 2., 1., 3., 4., 2., 3., 1., 2., 2., 3.,
	1., 2., 1., 3., 4., 2., 1., 1., 3., 2., 3., 2., 1., 4., 1., 2., 3.,
	1., 2., 3., 4., 1., 4., 2., 3., 4., 3., 1., 4., 2., 1., 2., 1., 4.,
	3., 2., 4., 3., 2., 1., 3., 4., 2., 3., 4., 1., 3., 4., 1., 4., 2.,
	3., 4., 3., 2., 1., 3., 4., 3., 1., 4., 2., 1., 4., 4., 2., 1., 3.,
	1., 2., 2., 1., 3., 4., 3., 2., 2., 3., 1., 2., 4., 1., 2., 3., 1.,
	2., 3., 1., 3., 2., 1., 4., 1., 2., 4., 2., 3., 4., 3., 1., 4., 2.,
	1., 4., 1., 2., 2., 4., 1., 4., 3., 2., 4., 2., 3., 1., 2., 3., 4.,
	2., 1., 4., 1., 2., 3., 2., 4., 4., 1., 3., 3., 2., 4., 4., 3., 2.,
	2., 1., 4., 3., 1., 4., 4., 3., 2., 4., 2., 3., 4., 3., 2., 4., 1.,
	2., 1., 4., 2., 4., 2., 3., 4., 3., 1., 3., 2., 1., 2., 1., 3., 4.,
	2., 3., 4., 2., 3., 2., 4., 3., 2., 1., 3., 2., 3., 1., 2., 3., 1.,
	2., 1., 3., 4., 1., 3., 2., 4., 1., 4., 1., 3., 4., 3., 2., 4., 1.,
	3., 4., 2., 3., 4., 3., 1., 2., 4., 1., 2., 1., 4., 4., 2., 1., 4.,
	2., 3., 3., 1., 4., 2., 3., 1., 4., 2., 1., 4., 3., 1., 4., 2., 3.,
	4., 1., 2., 2., 1., 3., 4., 1., 2., 2., 1., 3., 2., 1., 3., 3., 2.,
	1., 4., 1., 2., 4., 1., 3., 4., 3., 1., 1., 2., 3., 4., 3., 1., 3.,
	1., 2., 4., 3., 2., 4., 3., 2., 1., 4., 2., 1., 4., 2., 2., 3., 4.,
	2., 4., 1., 3., 1., 2., 2., 4., 3., 2., 1., 3., 2., 1., 3., 3., 1.,
	2., 4., 2., 3., 3., 4., 1., 2., 1., 3., 3., 1., 4., 3., 2., 1., 2.,
	1., 3., 2., 1., 3., 3., 1., 2., 4., 1., 2., 2., 4., 3., 4., 1., 2.,
	4., 1., 3., 4., 1., 2., 4., 3., 1., 2., 1., 3., 4., 3., 2., 3., 4.,
	1., 4., 1., 2., 4., 1., 2., 4., 1., 2., 2., 1., 4., 2., 4., 1., 3.,
	1., 4., 3., 1., 2., 4., 2., 3., 4., 2., 3., 4., 2., 1., 4., 3., 2.,
	2., 4., 3., 3., 1., 2., 1., 2., 3., 3., 2., 1., 3., 4., 2., 4., 3.,
	1., 4., 1., 2., 4., 3., 2., 4., 3., 1., 4., 1., 3., 2., 4., 1., 3.,
	2., 4., 2., 3., 1., 3., 2., 4., 3., 1., 4., 3., 2., 4., 4., 2., 3.,
	4., 2., 3., 4., 3., 2., 3., 4., 2., 3., 4., 1., 4., 1., 2., 1., 2.,
	4., 2., 4., 1., 4., 2., 3., 4., 3., 1., 4., 3., 2., 2., 4., 1., 4.,
	1., 3., 4., 1., 2., 4., 2., 3., 4., 3., 1., 4., 3., 1., 4., 3., 1.,
	4., 2., 1., 4., 3., 2., 2., 4., 3., 4., 1., 2., 3., 1., 4., 4., 1.,
	2., 3., 4., 1., 4., 3., 2., 4., 1., 2., 4., 1., 2., 4., 1., 2., 2.,
	4., 1., 4., 1., 2., 2., 4., 3., 4., 3., 1., 1., 4., 3., 4., 2., 3.,
	2., 1., 3., 2., 1., 4., 2., 4., 1., 3., 2., 1., 3., 1., 4., 2., 1.,
	4., 4., 3., 1., 4., 3., 2., 4., 2., 3., 3., 4., 2., 4., 1., 2., 4.,
	1., 3., 2., 3., 4., 2., 3., 4., 2., 1., 4., 4., 1., 3., 2., 4., 1.,
	4., 3., 2., 3., 1., 4., 3., 2., 4., 4., 2., 1., 4., 3., 2., 4., 3.,
	2., 2., 4., 3., 2., 1., 4., 2., 3., 1., 2., 3., 4., 4., 3., 2., 4.,
	2., 1., 4., 2., 1., 3., 2., 1., 3., 4., 1., 4., 3., 1., 4., 2., 3.,
	4., 1., 2., 2., 3., 4., 2., 3., 1., 4., 1., 3., 4., 2., 3., 2., 3.,
	4., 3., 4., 2., 4., 2., 3., 4., 3., 1., 4., 2., 1., 4., 3., 2., 3.,
	4., 1., 2., 3., 4., 2., 3., 4., 4., 3., 2., 4., 3., 2., 2., 1., 4.,
	4., 2., 1., 4., 2., 1., 3., 2., 1., 4., 2., 1., 4., 1., 3., 4., 2.,
	3., 4., 3., 1., 2., 1., 4., 4., 2., 3., 3., 4., 2., 4., 2., 3., 2.,
	3., 1., 2., 3., 4., 2., 1., 3., 4., 1., 3., 4., 2., 1., 2., 3., 4.,
	2., 4., 1., 3., 4., 1., 3., 1., 4., 4., 2., 3., 4., 2., 3., 4., 2.,
	3., 2., 3., 4., 3., 1., 4., 2., 1., 3., 4., 3., 1., 4., 2., 3., 2.,
	1., 4., 2., 3., 1., 4., 3., 1., 2., 3., 4., 3., 4., 1., 4., 1., 2.,
	4., 3., 1., 2., 1., 4., 1., 4., 3., 3., 1., 4., 2., 3., 4., 2., 3.,
	4., 4., 1., 3., 2., 1., 4., 3., 2., 4., 3., 2., 4., 4., 3., 1., 2.,
	4., 1., 4., 3., 2., 4., 1., 2., 4., 1., 2., 2., 4., 3., 3., 1., 2.,
	4., 2., 1., 3., 1., 4., 4., 2., 1., 3., 2., 4., 4., 3., 1., 4., 1.,
	2., 3., 1., 4., 3., 4., 1., 4., 1., 2., 4., 3., 2., 4., 3., 1., 4.,
	3., 2., 4., 1., 3., 2., 1., 3., 4., 1., 3., 3., 4., 1., 4., 1., 2.,
	4., 2., 3., 3., 2., 1., 1., 4., 2., 4., 2., 3., 3., 2., 4., 4., 2.,
	3., 4., 3., 1., 3., 4., 1., 3., 2., 4., 4., 3., 2., 2., 4., 3., 2.,
	3., 1., 3., 2., 1., 2., 1., 3., 4., 3., 1., 4., 1., 2., 2., 3., 4.,
	4., 2., 3., 4., 2., 1., 3., 4., 2., 3., 4., 1., 4., 2., 3., 2., 4.,
	3., 2., 3., 1., 2., 3., 1., 2., 1., 4., 3., 2., 4., 3., 1., 2., 1.,
	2., 4., 4., 3., 1., 2., 4., 1., 2., 4., 1., 4., 1., 3., 2., 1., 3.,
	2., 3., 4., 2., 1., 3., 4., 2., 3., 4., 3., 1., 2., 4., 1., 3., 1.,
	4., 3., 4., 2., 4., 3., 1., 3., 1., 2., 4., 1., 2., 3., 2., 1., 4.,
	1., 3., 4., 3., 1., 4., 3., 2., 3., 1., 4., 4., 2., 3., 4., 2., 1.,
	2., 4., 1., 4., 2., 3., 4., 2., 3., 2., 4., 1., 2., 1., 3., 2., 4.,
	1., 4., 1., 3., 2., 1., 3., 4., 1., 3., 2., 3., 4., 2., 4., 1., 4.,
	3., 1., 2., 3., 4., 3., 2., 4., 3., 1., 4., 4., 3., 2., 2., 4., 1.,
	2., 3., 1., 3., 4., 1., 4., 3., 2., 4., 3., 2., 4., 1., 3., 2., 1.,
	4., 3., 1., 4., 3., 2., 4., 4., 3., 1., 2., 3., 4., 4., 2., 3., 3.,
	2., 4., 1., 3., 4., 3., 1., 2., 3., 2., 4., 1., 2., 4., 4., 2., 3.,
	4., 1., 3., 2., 4., 1., 2., 4., 1., 3., 1., 2., 2., 1., 3., 2., 4.,
	1., 3., 2., 4., 4., 1., 2., 2., 4., 3., 4., 3., 1., 3., 2., 1., 2.,
	4., 3., 3., 2., 4., 2., 3., 1., 1., 3., 4., 3., 4., 2., 4., 1., 2.,
	4., 3., 2., 4., 2., 1., 4., 3., 2., 2., 1., 4., 4., 3., 2., 3., 4.,
	2., 2., 4., 1., 2., 1., 4., 4., 1., 3., 2., 1., 4., 4., 2., 3., 4.,
	3., 2., 4., 3., 2., 3., 4., 1., 4., 3., 2., 2., 1., 3., 2., 1., 4.,
	3., 2., 4., 3., 4., 2., 2., 1., 4., 3., 1., 4., 2., 1., 4., 3., 1.,
	2., 2., 4., 3., 2., 4., 1., 4., 1., 2., 4., 2., 1., 2., 1., 3., 4.,
	2., 1., 2., 4., 3., 2., 3., 4., 4., 1., 3., 2., 1., 4., 2., 1., 4.,
	4., 2., 1., 3., 4., 2., 4., 3., 1., 2., 1., 4., 4., 2., 3., 4., 2.,
	3., 4., 3., 2., 4., 1., 2., 1., 3., 4., 2., 1., 4., 3., 1., 2., 4.,
	3., 2., 4., 1., 3., 1., 2., 4., 3., 2., 1., 2., 1., 3., 4., 1., 3.,
	4., 2., 1., 4., 1., 2., 3., 1., 4., 2., 3., 4., 3., 4., 1., 2., 4.,
	3., 2., 4., 3., 4., 3., 2., 4., 3., 1., 3., 1., 4., 4., 1., 3., 4.,
	1., 2., 2., 1., 4., 4., 1., 2., 4., 1., 3., 2., 1., 4., 2., 4., 1.,
	4., 2., 3., 3., 1., 4., 4., 2., 1., 2., 4., 3., 2., 3., 1., 4., 3.,
	1., 4., 1., 2., 3., 2., 1., 2., 4., 1., 4., 1., 2., 2., 4., 3., 4.,
	1., 3., 4., 1., 2., 4., 2., 1., 2., 1., 3., 2., 3., 1., 4., 3., 2.,
	3., 1., 2., 2., 1., 4., 2., 4., 3., 4., 2., 3., 1., 2., 3., 2., 4.,
	1., 2., 3., 4., 3., 4., 2., 2., 3., 1., 2., 1., 4., 2., 1., 4., 2.,
	3., 1., 4., 3., 1., 4., 2., 3., 4., 1., 3., 2., 4., 3., 4., 3., 1.,
	4., 1., 3., 2., 3., 1., 3., 2., 4., 2., 3., 1., 2., 4., 1., 4., 3.,
	2., 4., 3., 1., 3., 2., 1., 4., 2., 1., 2., 3., 1., 2., 3., 1., 4.,
	1., 3., 4., 3., 1., 4., 2., 1., 4., 3., 2., 4., 1., 2., 2., 3., 4.,
	4., 2., 1., 4., 2., 3., 4., 1., 2., 3., 1., 2., 2., 4., 3., 3., 1.,
	2., 2., 4., 1., 2., 4., 3., 3., 4., 2., 4., 1., 3., 3., 4., 1., 4.,
	1., 3., 3., 4., 1., 3., 1., 4., 2., 1., 4., 4., 2., 3., 3., 4., 2.,
	3., 1., 4., 2., 3., 4., 4., 2., 1., 3., 4., 2., 4., 2., 1., 2., 4.,
	1., 4., 3., 2., 4., 1., 3., 4., 1., 3., 2., 1., 4., 4., 1., 3., 2.,
	3., 4., 4., 2., 1., 4., 2., 1., 4., 1., 2., 3., 2., 4., 4., 2., 1.,
	2., 1., 4., 2., 4., 1., 2., 1., 4., 4., 3., 2., 4., 1., 2., 3., 4.,
	1., 2., 3., 1., 3., 1., 2., 3., 4., 1., 4., 2., 3., 2., 3., 4., 4.,
	2., 1., 4., 2., 1., 4., 3., 2., 2., 3., 4., 3., 4., 2., 4., 2., 3.,
	2., 3., 1., 3., 1., 2., 2., 1., 4., 2., 3., 1., 3., 2., 1., 2., 3.,
	4., 3., 1., 4., 4., 2., 3., 4., 1., 3., 2., 3., 4., 2., 4., 3., 4.,
	2., 3., 4., 3., 2., 4., 3., 1., 1., 2., 3., 3., 2., 4., 4., 1., 2.,
	4., 3., 2., 4., 3., 1., 3., 4., 2., 4., 3., 1., 2., 1., 4., 4., 1.,
	2., 4., 1., 2., 3., 4., 2., 3., 1., 2., 4., 2., 1., 2., 1., 3., 4.,
	2., 1., 4., 1., 3., 4., 3., 2., 1., 2., 4., 4., 1., 2., 4., 2., 1.,
	4., 2., 1., 4., 2., 1., 2., 3., 4., 1., 3., 4., 4., 1., 2., 1., 4.,
	2., 4., 3., 1., 2., 4., 3., 4., 1., 3., 4., 2., 3., 1., 2., 4., 4.,
	1., 2., 2., 1., 4., 4., 1., 2., 4., 2., 3., 4., 3., 2., 4., 1., 3.,
	3., 1., 4., 1., 4., 2., 4., 2., 3., 2., 1., 4., 2., 1., 3., 4., 1.,
	3., 4., 3., 2., 4., 2., 3., 4., 3., 2., 3., 4., 1., 1., 2., 4., 4.,
	2., 1., 4., 2., 1., 4., 3., 2., 2., 3., 4., 4., 2., 3., 2., 1., 4.,
	4., 2., 1., 4., 3., 1., 4., 2., 1., 3., 2., 4., 2., 4., 1., 2., 4.,
	3., 4., 3., 2., 4., 1., 3., 2., 3., 1., 3., 1., 4., 2., 4., 1., 3.,
	1., 4., 3., 1., 4., 2., 3., 4., 2., 4., 1., 4., 3., 1., 3., 2., 1.,
	4., 2., 1., 2., 1., 3., 2., 3., 1., 4., 1., 2., 4., 1., 2., 4., 2.,
	3., 4., 3., 2., 2., 1., 3., 3., 1., 4., 4., 3., 1., 4., 3., 1., 4.,
	3., 2., 2., 4., 3., 2., 1., 4., 4., 3., 2., 2., 3., 4., 3., 2., 1.,
	4., 3., 2., 4., 2., 3., 4., 3., 1., 4., 2., 1., 3., 1., 2., 2., 3.,
	1., 3., 4., 2., 4., 3., 2., 3., 1., 2., 4., 3., 2., 3., 1., 4., 3.,
	4., 2., 3., 2., 1., 3., 4., 1., 4., 1., 2., 3., 4., 1., 3., 4., 2.,
	2., 1., 3., 3., 2., 1., 4., 1., 2., 3., 4., 1., 4., 1., 2., 4., 1.,
	2., 2., 3., 4., 3., 1., 2., 3., 1., 4., 4., 3., 2., 4., 1., 2., 3.,
	4., 1., 2., 1., 3., 3., 1., 4., 2., 3., 1., 2., 4., 3., 2., 3., 4.,
	4., 2., 3., 4., 3., 2., 3., 1., 2., 4., 3., 2., 4., 3., 2., 3., 4.,
	1., 2., 4., 3., 3., 4., 1.),
	.Dim = c(1941, 3)
	)
	)


Initial Values:

list(beta = structure(.Data=c(0, 0, 0, 0, 0, 0, 0, 0),
                      .Dim = c(4,2)),
     delta = structure(.Data=c(1, 1, 1, 1, 1, 1, 1, 1),
                      .Dim = c(4,2)),
     gamma  = structure(.Data=c(1, 2, 1, 2, 1, 2, 1, 2),
                      .Dim = c(4,2))
)



Results:

	 node	 mean	 sd	 MC error	2.5%	median	97.5%	start	sample
	beta[1,1]	1.373	0.1055	0.00858	1.185	1.37	1.593	6001	200
	beta[1,2]	1.182	0.157	0.01517	0.9228	1.173	1.505	6001	200
	beta[2,1]	2.779	0.2002	0.02714	2.43	2.767	3.21	6001	200
	beta[2,2]	1.346	0.1835	0.02598	1.024	1.323	1.751	6001	200
	beta[3,1]	2.799	0.1701	0.01308	2.488	2.79	3.184	6001	200
	beta[3,2]	0.9911	0.1438	0.01107	0.7316	0.9898	1.3	6001	200
	beta[4,1]	0.793	0.08509	0.006734	0.6348	0.7876	0.9601	6001	200
	beta[4,2]	0.8384	0.1505	0.01496	0.5525	0.8418	1.098	6001	200

	 node	 mean	 sd	 MC error	2.5%	median	97.5%	start	sample
	delta[1,1]	0.7451	0.339	0.01867	0.1018	0.7391	1.48	4001	500
	delta[1,2]	1.435	0.5014	0.02862	0.5654	1.394	2.457	4001	500
	delta[2,1]	0.5585	0.1342	0.009755	0.2773	0.5621	0.8073	4001	500
	delta[2,2]	0.2701	0.2283	0.0198	-0.1123	0.2574	0.7499	4001	500
	delta[3,1]	0.7423	0.1712	0.01142	0.4293	0.7389	1.114	4001	500
	delta[3,2]	0.8334	0.2755	0.0251	0.3305	0.8423	1.355	4001	500
	delta[4,1]	1.125	0.1124	0.0084	0.8964	1.127	1.361	4001	500
	delta[4,2]	0.357	0.1603	0.01333	0.07989	0.3539	0.6658	4001	500

	 node	 mean	 sd	 MC error	2.5%	median	97.5%	start	sample
	gamma[1,1]	2.187	0.1218	0.007896	1.966	2.187	2.469	4001	300
	gamma[1,2]	3.691	0.1798	0.01237	3.36	3.677	4.077	4001	300
	gamma[2,1]	2.19	0.1442	0.01412	1.923	2.173	2.511	4001	300
	gamma[2,2]	3.599	0.2028	0.02026	3.263	3.575	4.024	4001	300
	gamma[3,1]	1.64	0.1168	0.009212	1.413	1.635	1.886	4001	300
	gamma[3,2]	2.877	0.1539	0.01085	2.616	2.865	3.2	4001	300
	gamma[4,1]	2.1	0.0915	0.007492	1.926	2.102	2.273	4001	300
	gamma[4,2]	3.141	0.1197	0.01033	2.928	3.139	3.374	4001	300
